# Generated by Codex on 2026-05-15
from django.db import migrations


def seed_disciplinas(apps, schema_editor):
    Disciplina = apps.get_model("core", "Disciplina")
    disciplinas = [
        ("Civil", "ingenieria"),
        ("Mecanica", "ingenieria"),
        ("Electrica", "ingenieria"),
        ("RRHH", "administrativo"),
        ("Compras", "administrativo"),
        ("Gerencia de Proyectos", "gerencia"),
    ]
    for nombre, area in disciplinas:
        Disciplina.objects.update_or_create(
            nombre=nombre,
            defaults={"area": area},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_disciplinas, migrations.RunPython.noop),
    ]
