# Generated by Django 6.0.1 on 2026-06-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_calidad_role_googledrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopaldaca',
            name='telefono',
            field=models.CharField(blank=True, help_text='Telefono del usuario', max_length=20, null=True, verbose_name='Telefono'),
        ),
    ]
