# Generated by Django 5.2.4 on 2025-07-28 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('ultimo_numero', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('correo_notificacion', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.CharField(max_length=4)),
                ('numero_proyecto', models.CharField(max_length=2)),
                ('subproyecto', models.CharField(max_length=1)),
                ('departamento', models.CharField(max_length=2)),
                ('disciplina', models.CharField(max_length=2)),
                ('tipo_documento', models.CharField(max_length=4)),
                ('consecutivo', models.PositiveIntegerField()),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos.empresa')),
            ],
        ),
    ]
