# Generated by Django 5.2.4 on 2025-08-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigogenerado',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
