# Generated by Django 5.2.4 on 2025-07-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.CharField(max_length=4)),
                ('numero_proyecto', models.CharField(max_length=2)),
                ('subproyecto', models.CharField(max_length=1)),
                ('departamento', models.CharField(max_length=2)),
                ('disciplina', models.CharField(max_length=2)),
                ('tipo_documento', models.CharField(max_length=4)),
                ('consecutivo', models.PositiveIntegerField()),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
