# Generated by Django 5.1.6 on 2025-07-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_codigogenerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigogenerado',
            name='empresa',
            field=models.CharField(default='PAL', max_length=3),
        ),
    ]
