# Generated by Django 5.2.4 on 2025-08-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_solicitudanulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigogenerado',
            name='motivo',
            field=models.TextField(default='Sin Motivo', verbose_name='Motivo / Asunto'),
            preserve_default=False,
        ),
    ]
