"""
Django settings for codigos project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


import os
import logging
from pathlib import Path
from .db import DATABASEDES, DATABASEPROD
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
_key_env = BASE_DIR / "key.env"
_dev_env = BASE_DIR / "dev.env"
if _key_env.exists():
    load_dotenv(_key_env)
else:
    load_dotenv(BASE_DIR / ".env" / "key.env")
if _dev_env.exists():
    load_dotenv(_dev_env, override=True)
load_dotenv(dotenv_path=os.path.join(BASE_DIR, "correo.env"))
LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY:
    raise ValueError(
        "DJANGO_SECRET_KEY no definida. Copia key.env desde Portal-Paldaca "
        "(misma clave y MYSQL_*) a la raiz de Codigos."
    )

# SECURITY WARNING: don't run with debug turned on in production!
# Sin DJANGO_DEBUG: true solo si hay dev.env (local); en servidor queda false.
DEBUG = True

ALLOWED_HOSTS = [
    'codigos.cpaldaca.com',
    'www.codigos.cpaldaca.com',
    'localhost',
    '127.0.0.1',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'documentos',
    'widget_tweaks'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Despues de Authentication (necesita request.user) y ANTES de
    # PaldacaSessionMiddleware (que puede cortocircuitar y necesita saber si la
    # peticion viene embebida). Su fase de respuesta corre despues de todos los
    # de abajo, asi que tiene la ultima palabra sobre las cabeceras de framing.
    'core.embed.PaldacaEmbedMiddleware',
    'core.middleware.PaldacaSessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # XFrameOptionsMiddleware retirado: emitia X-Frame-Options: DENY (default de
    # Django al no definir X_FRAME_OPTIONS), lo que impide embeber el modulo en
    # el shell del Portal. El control de framing lo hace ahora PaldacaEmbedMiddleware
    # con CSP frame-ancestors, que si admite lista de origenes.
]

ROOT_URLCONF = 'codigos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.paldaca_urls',
                'core.context_processors.navigation_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'codigos.wsgi.application'

# Cambio de prueba
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Local: existe dev.env → DATABASEDES. Producción (sin dev.env) → DATABASEPROD.
DATABASES = DATABASEDES if _dev_env.exists() else DATABASEPROD

AUTH_USER_MODEL = "core.UsuarioPaldaca"

PALDACA_SSO_LOGIN_URL = os.getenv("PALDACA_SSO_LOGIN_URL", "http://localhost:5173/login/")
PALDACA_SSO_LOGOUT_URL = os.getenv(
    "PALDACA_SSO_LOGOUT_URL",
    "http://localhost:8000/api/auth/sso/logout/",
)
PALDACA_STRICT_SESSION_CONSISTENCY = os.getenv(
    "PALDACA_STRICT_SESSION_CONSISTENCY",
    "true",
)

# --- Portal unificado: este modulo embebido en el shell ---------------------
PALDACA_MODULO_CODIGO = "codigos"

PALDACA_PORTAL_URL = (
    (os.getenv("PALDACA_PORTAL_URL") or "").strip().rstrip("/")
    or ("http://localhost:5173" if DEBUG else "https://cpaldaca.com")
)

PALDACA_SHELL_PATH = os.getenv("PALDACA_SHELL_PATH", "/codigos")

_frame_ancestors = ["'self'", PALDACA_PORTAL_URL]
if DEBUG:
    _frame_ancestors += ["http://localhost:5173", "http://127.0.0.1:5173"]
else:
    _frame_ancestors += ["https://cpaldaca.com", "https://www.cpaldaca.com"]
PALDACA_FRAME_ANCESTORS = os.getenv(
    "PALDACA_FRAME_ANCESTORS",
    " ".join(dict.fromkeys(a for a in _frame_ancestors if a)),
)

PALDACA_EMBED_REDIRECT_TO_SHELL = os.getenv(
    "PALDACA_EMBED_REDIRECT_TO_SHELL",
    "false",
).lower() == "true"

SESSION_COOKIE_NAME = os.getenv("SESSION_COOKIE_NAME", "paldaca_sessionid")
_raw_cookie_domain = (os.getenv("SESSION_COOKIE_DOMAIN") or "").strip()
SESSION_COOKIE_DOMAIN = (
    f".{_raw_cookie_domain.lstrip('.')}" if _raw_cookie_domain else None
)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = (
    os.getenv("SESSION_COOKIE_SECURE", "true" if SESSION_COOKIE_DOMAIN else "false").lower()
    == "true"
)
CSRF_COOKIE_DOMAIN = SESSION_COOKIE_DOMAIN
CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE

if DEBUG and not _raw_cookie_domain:
    SESSION_COOKIE_DOMAIN = None
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_DOMAIN = None
    CSRF_COOKIE_SECURE = False
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:5173",
        "http://localhost:8000",
        "http://localhost:8001",
        "http://localhost:8002",
        "http://localhost:8003",
    ]
elif SESSION_COOKIE_DOMAIN:
    CSRF_TRUSTED_ORIGINS = [
        "https://cpaldaca.com",
        "https://www.cpaldaca.com",
        "https://api.cpaldaca.com",
        "https://codigos.cpaldaca.com",
        "https://www.codigos.cpaldaca.com",
    ]
else:
    CSRF_TRUSTED_ORIGINS = [
        "https://cpaldaca.com",
        "https://www.cpaldaca.com",
        "https://api.cpaldaca.com",
        "https://codigos.cpaldaca.com",
        "https://www.codigos.cpaldaca.com",
    ]

LOGIN_URL = PALDACA_SSO_LOGIN_URL
LOGOUT_REDIRECT_URL = PALDACA_SSO_LOGOUT_URL

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'codigos.cpaldaca.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True         # ✅ Usa SSL ya que el puerto es 465
EMAIL_USE_TLS = False        # ❌ TLS debe estar desactivado si usas SSL
EMAIL_HOST_USER = 'admin@codigos.cpaldaca.com'
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # Se carga desde correo.env
DEFAULT_FROM_EMAIL = 'admin@codigos.cpaldaca.com'
#print('PASS:', os.getenv('EMAIL_HOST_PASSWORD'))

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ve'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [ BASE_DIR / "documentos" / "static" ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s [%(levelname)s] %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'app_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'app.log'),
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'errors.log'),
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'level': 'ERROR',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'documentos': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'app_file', 'error_file'],
        'level': 'INFO',
    },
}
